### ISSUE TITLE
Révision du Readme

### ISSUE THREAD

**Issue by ipante** [Doun92/rest#3]
"Comment proposer un lit" devrait sans doute être un sous-titre d'une section plus générale "description". Par ailleurs, il est étrange de voir jQuery et Bootstrap en-dehors des plugins installés. Vous pourriez sans doute les y placer.

Dernière remarque : pourquoi ne pas proposer une image d'illustration de votre projet?

**Comment by Aubrays** [comment]
Les liens des images sont maintenant fonctionnels.

**Comment by LRimaz** [comment]
Hello, on a refait le test avec une installation vierge, pas de problème avec le dropdown. On a juste fait:
`meteor npm install`

**Comment by ipante** [comment]
Dès que tous les problèmes sont résolus, n'oubliez pas de fermer l'issue!

**Comment by Aubrays** [comment]
@DigitalDW Merci. J'ai testé et effectivement, ça fonctionne bien comme tu le décris. J'ai mis à jour le readme en conséquence.
